version: '3.2'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php
      - mysql
      - mysql_test
    networks:
      backend:
      frontend:
        ipv4_address: 10.5.0.6
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.2'
        DOCKER_PHP_ENABLE_XDEBUG: 'on'
        DOCKER_PHP_XDEBUG_VERSION: '2.9.2'
    working_dir: /var/www/app
    container_name: php
    volumes:
      - .:/var/www/app
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9001:9000"
    extra_hosts:
      - "testapi.birqsil.ru:10.5.0.6"
      - "testfrontapi.birqsil.ru:10.5.0.6"
    networks:
      backend:
      frontend:
        ipv4_address: 10.5.0.5

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql/
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=birqsil
      - MYSQL_USER=supermetrolog
      - MYSQL_PASSWORD=12345
    networks:
      - backend

  mysql_test:
    image: mysql
    container_name: mysql_test
    restart: always
    volumes:
      - ./docker/mysql/data_test:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql/
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=birqsil_test
      - MYSQL_USER=supermetrolog
      - MYSQL_PASSWORD=12345
    networks:
      - backend

networks:
  backend:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1