#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */
require __DIR__ . '/vendor/autoload.php';

$local = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/local.php',
    require __DIR__ . '/console/config/local.php'
);

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/config.php',
    require __DIR__ . '/console/config/config.php',
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
